shell.run("wget https://raw.githubusercontent.com/ItsZariiia/pocket-dialler/refs/heads/dev/client/ClientMain.lua")
shell.run("wget https://raw.githubusercontent.com/ItsZariiia/pocket-dialler/refs/heads/dev/client/ClientMonitorInterface.lua")
shell.run("wget https://raw.githubusercontent.com/ItsZariiia/pocket-dialler/refs/heads/dev/client/ClientTerminalInterface.lua")
shell.run("wget https://raw.githubusercontent.com/ItsZariiia/pocket-dialler/refs/heads/dev/common/startup.lua")
shell.run("wget https://raw.githubusercontent.com/ItsZariiia/pocket-dialler/refs/heads/dev/common/Util.lua")
shell.run("wget https://raw.githubusercontent.com/ItsZariiia/pocket-dialler/refs/heads/dev/common/AddressBook.lua")
shell.run("wget https://raw.githubusercontent.com/ItsZariiia/pocket-dialler/refs/heads/dev/server/ServerMain.lua")
shell.run("wget https://raw.githubusercontent.com/ItsZariiia/pocket-dialler/refs/heads/dev/server/StargateHandler.lua")
shell.run("wget https://raw.githubusercontent.com/ItsZariiia/pocket-dialler/refs/heads/dev/addresses.conf")

shell.run("wget run https://raw.githubusercontent.com/Pyroxenium/Basalt2/main/install.lua -f")
